### ISSUE TITLE
Admin pass

### ISSUE THREAD

**Issue by Ygorgo96** [Sam-Tech-2543/MCQ-Examination#1]
Hello, what is the password for the administrator panel?

**Comment by SarveshMankar** [comment]
$uname="a";
    $pwd="a";

**Comment by Qhashan** [comment]
Is it possible to participate without sign in
Or option open quiz with out login?

**Comment by SarveshMankar** [comment]
> Is it possible to participate without sign in Or option open quiz with out login?

No. Ideologically, the admin needs to log in to manage quizzes, and the student needs to provide the information to attempt a quiz.
